# Generated by Django 3.0.4 on 2022-12-13 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_categoria'),
        ('triagem', '0004_auto_20221213_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='contatou',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_diarreia',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_dificuldade_respiratoria',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_dor_cabeca',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_dores_corpo',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_febre',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_irritacao_garganta',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_secrecao_espirros',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='tem_tosse',
        ),
        migrations.RemoveField(
            model_name='triagem',
            name='viajou',
        ),
        migrations.AddField(
            model_name='triagem',
            name='alta',
            field=models.BooleanField(default=False, verbose_name='Teve Alta?'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='unidade.Categoria', verbose_name='Categoria do Atendimento *'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='cdm',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CDM'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='prec',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='PREC CP'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='pront',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimento *'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='rx',
            field=models.BooleanField(default=False, verbose_name='Teve RX ?'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='urgencia',
            field=models.BooleanField(default=False, verbose_name='É Urgente?'),
        ),
        migrations.AddField(
            model_name='triagem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='VALOR (R$)'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.5)], verbose_name='Altura em metros'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Use dd/mm/aaaa', max_length=10, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(400.0)], verbose_name='Peso em kg'),
        ),
    ]
