# Generated by Django 3.0.4 on 2022-12-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0003_auto_20221213_1409'),
        ('triagem', '0005_auto_20221213_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagem',
            name='proncedimento',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimento *'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='unidade.Categoria', verbose_name='Situação Mil *'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='pront',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pront'),
        ),
    ]
