# Generated by Django 3.0.4 on 2022-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Categoria de Atendimento *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o curso pode ser usado no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
        ),
    ]
