# Generated by Django 3.0.4 on 2022-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Situação do Militar *'),
        ),
    ]
